### ISSUE TITLE
Err` value: SocketSetMaxHops("Protocol not available (os error 92)") on Linux

### ISSUE THREAD

**Issue by zaphar** [dev-bio/Ekko#1]
Sending the packet on linux seems to fail with the above error. Windows it works fine.

**Comment by zaphar** [comment]
You can see the code I'm using here: https://github.com/zaphar/durnitisp/blob/ping_support/src/icmp.rs

**Comment by zaphar** [comment]
I've done some more digging and it appears that this only happens for IPv6 addresses. In https://github.com/dev-bio/Ekko/blob/master/src/sender.rs#L69 you use the set_ttl method regardless of the type of socket but that option is only for ipv4 addresses so it fails with the Protocol not available error since that option isn't available for ipv6. You need to use `set_unicast_hops` I believe if the address is an IPv6 address.

**Comment by dev-bio** [comment]
I'm currently on holiday, please take a look at my latest commit: 84f122b3cf71dc080b923e308a86117a61ec4b85

**Comment by dev-bio** [comment]
Tested without problems on Windows, so if you could confirm that this resolves the issue on Linux I will merge these changes into master.

**Comment by zaphar** [comment]
I will look at this later this evening. I'm afraid I went on holiday a few days after my initial report as well :-D

**Comment by zaphar** [comment]
I've verified that we no longer trigger this error on linux for IPV6 addresses.
