### ISSUE TITLE
Include the Sequence Number in EkkoData

### ISSUE THREAD

**Issue by zaphar** [dev-bio/Ekko#3]
It's useful for long running pings to handle out of order packets among other things that can occur. I may try to put together a PR for this later.

**Comment by dev-bio** [comment]
06105d3

Packets will not be handled out of order, it will only listen for the current sequence number up until it times out.

**Comment by dev-bio** [comment]
Closing for now, get back to me if there's something I missed.

_Thank you!_

**Comment by dev-bio** [comment]
[This has now been included.](https://github.com/dev-bio/Ekko/blob/c47dc5c6c43a908dae7b3d8ffd2deb4415d3345e/src/responses.rs#L101-L104)
